Add support for deflate and snappy codecs
flix-tech/avro-php pull request #9
Opened 2020-09-27 21:26 UTC by smalot

2020-09-27 22:19 UTC, smalot commented
Hi @tPl0ch 
Could you double check this PR ?

2020-09-29 08:54 UTC, tPl0ch requested changes
Thanks, there are just a few minor comments - mainly getting rid of the iterations in the tests via a data provider.

2020-09-29 08:54 UTC, tPl0ch commented on test/data/users.json
> +{"name":"Alyssa","favorite_color":null,"favorite_numbers":[3,9,15,20]}
Should have a newline at end of file

2020-09-29 08:54 UTC, tPl0ch commented on test/DataFileTest.php
> +    foreach (AvroDataIO::valid_codecs() as $codec) {
Should be refactored into a PHPUnit data provider and used via the `@dataProvider` annotation.

2020-09-29 08:54 UTC, tPl0ch commented on test/DataFileTest.php
> +    foreach (AvroDataIO::valid_codecs() as $codec) {
Can re-use above data provider for codecs.

2020-09-29 08:54 UTC, tPl0ch commented on test/DataFileTest.php
> +    foreach (AvroDataIO::valid_codecs() as $codec) {
Can re-use above data provider for codecs.

2020-09-29 08:54 UTC, tPl0ch commented on test/DataFileTest.php
> +    foreach (AvroDataIO::valid_codecs() as $codec) {
Can re-use above data provider for codecs.

2020-09-29 08:54 UTC, tPl0ch commented on test/DataFileTest.php
> +    foreach (AvroDataIO::valid_codecs() as $codec) {
Can re-use above data provider for codecs.

2020-09-29 08:54 UTC, tPl0ch commented on test/DataFileTest.php
> +    foreach (AvroDataIO::valid_codecs() as $codec) {
Can re-use above data provider for codecs.

2020-09-29 08:54 UTC, tPl0ch commented on test/DataFileTest.php
> +    foreach (AvroDataIO::valid_codecs() as $codec) {
Can re-use above data provider for codecs.

2020-09-29 08:54 UTC, tPl0ch commented on test/DataFileTest.php
> +    foreach (AvroDataIO::valid_codecs() as $codec) {
Can re-use above data provider for codecs.

2020-09-29 08:54 UTC, tPl0ch commented on test/DataFileTest.php
> +    foreach (AvroDataIO::valid_codecs() as $codec) {
Can re-use above data provider for codecs.

2020-09-29 08:54 UTC, tPl0ch commented on test/DataFileTest.php
> +    foreach (AvroDataIO::valid_codecs() as $codec) {
Can re-use above data provider for codecs.

2020-09-29 22:21 UTC, smalot commented on test/data/users.json
> +{"name":"Alyssa","favorite_color":null,"favorite_numbers":[3,9,15,20]}
Indeed

2020-09-29 22:22 UTC, smalot commented on test/DataFileTest.php
> +    foreach (AvroDataIO::valid_codecs() as $codec) {
Not sure to understand what you want.
Can you provide me an example ?

2020-09-29 22:28 UTC, smalot commented on test/DataFileTest.php
> +    foreach (AvroDataIO::valid_codecs() as $codec) {
I think I understand
I'll try something

https://phpunit.de/manual/3.7/en/writing-tests-for-phpunit.html#writing-tests-for-phpunit.data-providers

2020-09-30 10:58 UTC, smalot commented on test/data/users.json
> +{"name":"Alyssa","favorite_color":null,"favorite_numbers":[3,9,15,20]}
Fixed

2020-09-30 11:00 UTC, smalot commented
@tPl0ch  Should be good, can you check on your side ?

2020-09-30 11:12 UTC, tPl0ch approved these changes
LGTM

2020-09-30 11:13 UTC, merged

2020-09-30 12:43 UTC, smalot commented
Thank you @tPl0ch